### ISSUE TITLE
why the cicp tag is not matched with the code point values in ITU-T Rec.Series H Supplement

### ISSUE THREAD

**Issue by GrousexyHKCN** [digitaltvguy/ICC-v4.4-Profiles-with-CICP-Tags-for-HDR-and-SDR-Broadcast-Applications#1]
hoping i am not asking a stupid question since i am freshman to CICP.
when i use color management tool to check these ICC profile, i found the code point value in tag 'CICP' is not as expected
<img width="641" alt="image" src="https://github.com/digitaltvguy/ICC-v4.4-Profiles-with-CICP-Tags-for-HDR-and-SDR-Broadcast-Applications/assets/148685507/bc6d09f8-e24e-4676-864f-2db5873a4a16">

in the red bracket, the four values account the code point value for: color primaries, transfer characteristics, matrix coeffs and chromaLoc Type right?
i think PQ should be 16 and HLG should be 18, but in the file PQ shows 10 and HLG shows 12.

**Comment by digitaltvguy** [comment]
Hi,

Thank you for the question. I think this is related to translating between signed and unsigned values.  If you download MediaInfo, you should see the translated values.  You may also view with https://hexed.it.
